version: "3"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "postgres-db"
    restart: always
    volumes:
      - ./db-postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: 123

volumes:
  db-postgres-volume:
